name: flutter_speed_dialer
description: A FAB speed dialer for Flutter.
version: 0.0.2
author: Hayden Flinner <hayden@flinner.me>
homepage: https://github.com/haydenflinner/flutter_speed_dialer

environment:
  sdk: "<2.0.0"

dev_dependencies:
  test: ^0.12.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec